USETEXTLINKS = 1
STARTALLOPEN = 0
HIGHLIGHT = 1
HIGHLIGHT_BG = "gray"
PRESERVESTATE = 1
GLOBALTARGET="R"
BUILDALL = 0
USEICONS = 0
USEFRAMES = 1
WRAPTEXT = 0
ICONPATH = "images/"

foldersTree = gFld("Database Documentation", "PostgreSQL.localhost.OauthDB/default.htm")
f0 = gFld("localhost.OauthDB (PostgreSQL)", "PostgreSQL.localhost.OauthDB/default.htm")
f0_0 = gFld("Tables", "PostgreSQL.localhost.OauthDB/allTables.htm")
f0_0_0 = gFld("public", "")
f0_0_0_0 = gFld("accesstokens", "PostgreSQL.localhost.OauthDB/table_publicaccesstokens.htm")
f0_0_0_1 = gFld("authorizationcodes", "PostgreSQL.localhost.OauthDB/table_publicauthorizationcodes.htm")
f0_0_0_2 = gFld("clients", "PostgreSQL.localhost.OauthDB/table_publicclients.htm")
f0_0_0_3 = gFld("logstatus", "PostgreSQL.localhost.OauthDB/table_publiclogstatus.htm")
f0_0_0_4 = gFld("logtable", "PostgreSQL.localhost.OauthDB/table_publiclogtable.htm")
f0_0_0_5 = gFld("patches", "PostgreSQL.localhost.OauthDB/table_publicpatches.htm")
f0_0_0_6 = gFld("refreshtokens", "PostgreSQL.localhost.OauthDB/table_publicrefreshtokens.htm")
f0_0_0_7 = gFld("roles", "PostgreSQL.localhost.OauthDB/table_publicroles.htm")
f0_0_0_8 = gFld("scopes", "PostgreSQL.localhost.OauthDB/table_publicscopes.htm")
f0_0_0_9 = gFld("scopesroles", "PostgreSQL.localhost.OauthDB/table_publicscopesroles.htm")
f0_0_0_10 = gFld("users", "PostgreSQL.localhost.OauthDB/table_publicusers.htm")
f0_0_0_11 = gFld("usersroles", "PostgreSQL.localhost.OauthDB/table_publicusersroles.htm")
f0_0.addChildren([f0_0_0])
f0_0_0.addChildren([f0_0_0_0,f0_0_0_1,f0_0_0_2,f0_0_0_3,f0_0_0_4,f0_0_0_5,f0_0_0_6,f0_0_0_7,f0_0_0_8,f0_0_0_9,f0_0_0_10,f0_0_0_11])
f0_3 = gFld("Functions", "PostgreSQL.localhost.OauthDB/allUDFs.htm")
f0_3_0 = gFld("public", "")
f0_3_0_0 = gFld("createauthorizationcode", "PostgreSQL.localhost.OauthDB/udf_publiccreateauthorizationcode.htm")
f0_3_0_1 = gFld("createclient", "PostgreSQL.localhost.OauthDB/udf_publiccreateclient.htm")
f0_3_0_2 = gFld("createlog", "PostgreSQL.localhost.OauthDB/udf_publiccreatelog.htm")
f0_3_0_3 = gFld("createrefreshtoken", "PostgreSQL.localhost.OauthDB/udf_publiccreaterefreshtoken.htm")
f0_3_0_4 = gFld("createrole", "PostgreSQL.localhost.OauthDB/udf_publiccreaterole.htm")
f0_3_0_5 = gFld("createscope", "PostgreSQL.localhost.OauthDB/udf_publiccreatescope.htm")
f0_3_0_6 = gFld("createscopesroles", "PostgreSQL.localhost.OauthDB/udf_publiccreatescopesroles.htm")
f0_3_0_7 = gFld("createuser", "PostgreSQL.localhost.OauthDB/udf_publiccreateuser.htm")
f0_3_0_8 = gFld("createuser", "PostgreSQL.localhost.OauthDB/udf_publiccreateuser.htm")
f0_3_0_9 = gFld("createusersroles", "PostgreSQL.localhost.OauthDB/udf_publiccreateusersroles.htm")
f0_3_0_10 = gFld("deleteauthorizationcode", "PostgreSQL.localhost.OauthDB/udf_publicdeleteauthorizationcode.htm")
f0_3_0_11 = gFld("deleterefreshtoken", "PostgreSQL.localhost.OauthDB/udf_publicdeleterefreshtoken.htm")
f0_3_0_12 = gFld("getaccesstoken", "PostgreSQL.localhost.OauthDB/udf_publicgetaccesstoken.htm")
f0_3_0_13 = gFld("getauthorizationcode", "PostgreSQL.localhost.OauthDB/udf_publicgetauthorizationcode.htm")
f0_3_0_14 = gFld("getclient", "PostgreSQL.localhost.OauthDB/udf_publicgetclient.htm")
f0_3_0_15 = gFld("getclientbyid", "PostgreSQL.localhost.OauthDB/udf_publicgetclientbyid.htm")
f0_3_0_16 = gFld("getrefreshtoken", "PostgreSQL.localhost.OauthDB/udf_publicgetrefreshtoken.htm")
f0_3_0_17 = gFld("getuser", "PostgreSQL.localhost.OauthDB/udf_publicgetuser.htm")
f0_3_0_18 = gFld("getuserbyexternalid", "PostgreSQL.localhost.OauthDB/udf_publicgetuserbyexternalid.htm")
f0_3_0_19 = gFld("getuserbyid", "PostgreSQL.localhost.OauthDB/udf_publicgetuserbyid.htm")
f0_3_0_20 = gFld("getuserfromclient", "PostgreSQL.localhost.OauthDB/udf_publicgetuserfromclient.htm")
f0_3_0_21 = gFld("savetoken", "PostgreSQL.localhost.OauthDB/udf_publicsavetoken.htm")
f0_3_0_22 = gFld("setuser", "PostgreSQL.localhost.OauthDB/udf_publicsetuser.htm")
f0_3.addChildren([f0_3_0])
f0_3_0.addChildren([f0_3_0_0,f0_3_0_1,f0_3_0_2,f0_3_0_3,f0_3_0_4,f0_3_0_5,f0_3_0_6,f0_3_0_7,f0_3_0_8,f0_3_0_9,f0_3_0_10,f0_3_0_11,f0_3_0_12,f0_3_0_13,f0_3_0_14,f0_3_0_15,f0_3_0_16,f0_3_0_17,f0_3_0_18,f0_3_0_19,f0_3_0_20,f0_3_0_21,f0_3_0_22])
f0_8 = gFld("Types", "PostgreSQL.localhost.OauthDB/allUDTs.htm")
f0_8_0 = gFld("public._accesstokens", "PostgreSQL.localhost.OauthDB/udt_public_accesstokens.htm")
f0_8_1 = gFld("public._authorizationcodes", "PostgreSQL.localhost.OauthDB/udt_public_authorizationcodes.htm")
f0_8_2 = gFld("public._clients", "PostgreSQL.localhost.OauthDB/udt_public_clients.htm")
f0_8_3 = gFld("public._dblink_pkey_results", "PostgreSQL.localhost.OauthDB/udt_public_dblink_pkey_results.htm")
f0_8_4 = gFld("public._logstatus", "PostgreSQL.localhost.OauthDB/udt_public_logstatus.htm")
f0_8_5 = gFld("public._logtable", "PostgreSQL.localhost.OauthDB/udt_public_logtable.htm")
f0_8_6 = gFld("public._patches", "PostgreSQL.localhost.OauthDB/udt_public_patches.htm")
f0_8_7 = gFld("public._refreshtokens", "PostgreSQL.localhost.OauthDB/udt_public_refreshtokens.htm")
f0_8_8 = gFld("public._roles", "PostgreSQL.localhost.OauthDB/udt_public_roles.htm")
f0_8_9 = gFld("public._scopes", "PostgreSQL.localhost.OauthDB/udt_public_scopes.htm")
f0_8_10 = gFld("public._scopesroles", "PostgreSQL.localhost.OauthDB/udt_public_scopesroles.htm")
f0_8_11 = gFld("public._users", "PostgreSQL.localhost.OauthDB/udt_public_users.htm")
f0_8_12 = gFld("public._usersroles", "PostgreSQL.localhost.OauthDB/udt_public_usersroles.htm")
f0_8_13 = gFld("public.dblink_pkey_results", "PostgreSQL.localhost.OauthDB/udt_publicdblink_pkey_results.htm")
f0_8.addChildren([f0_8_0,f0_8_1,f0_8_2,f0_8_3,f0_8_4,f0_8_5,f0_8_6,f0_8_7,f0_8_8,f0_8_9,f0_8_10,f0_8_11,f0_8_12,f0_8_13])
f0_10 = gFld("Schemas", "PostgreSQL.localhost.OauthDB/allSchemas.htm")
f0_10_0 = gFld("pg_toast_temp_1", "PostgreSQL.localhost.OauthDB/schema_pg_toast_temp_1.htm")
f0_10_1 = gFld("public", "PostgreSQL.localhost.OauthDB/schema_public.htm")
f0_10.addChildren([f0_10_0,f0_10_1])
f0_12 = gFld("Indexes", "PostgreSQL.localhost.OauthDB/allIndexes.htm")
f0_12_0 = gFld("public.accesstokens__un", "PostgreSQL.localhost.OauthDB/index_publicaccesstokens__un.htm")
f0_12_1 = gFld("public.accesstokens_pk", "PostgreSQL.localhost.OauthDB/index_publicaccesstokens_pk.htm")
f0_12_2 = gFld("public.authorizationcodes__un", "PostgreSQL.localhost.OauthDB/index_publicauthorizationcodes__un.htm")
f0_12_3 = gFld("public.authorizationcodes_pk", "PostgreSQL.localhost.OauthDB/index_publicauthorizationcodes_pk.htm")
f0_12_4 = gFld("public.clients_pk", "PostgreSQL.localhost.OauthDB/index_publicclients_pk.htm")
f0_12_5 = gFld("public.logstatus_pk", "PostgreSQL.localhost.OauthDB/index_publiclogstatus_pk.htm")
f0_12_6 = gFld("public.logtable_pk", "PostgreSQL.localhost.OauthDB/index_publiclogtable_pk.htm")
f0_12_7 = gFld("public.refreshtockens_pk", "PostgreSQL.localhost.OauthDB/index_publicrefreshtockens_pk.htm")
f0_12_8 = gFld("public.refreshtokens__un", "PostgreSQL.localhost.OauthDB/index_publicrefreshtokens__un.htm")
f0_12_9 = gFld("public.roles__un", "PostgreSQL.localhost.OauthDB/index_publicroles__un.htm")
f0_12_10 = gFld("public.roles_pk", "PostgreSQL.localhost.OauthDB/index_publicroles_pk.htm")
f0_12_11 = gFld("public.scopes__un", "PostgreSQL.localhost.OauthDB/index_publicscopes__un.htm")
f0_12_12 = gFld("public.scopes_pk", "PostgreSQL.localhost.OauthDB/index_publicscopes_pk.htm")
f0_12_13 = gFld("public.users__un", "PostgreSQL.localhost.OauthDB/index_publicusers__un.htm")
f0_12_14 = gFld("public.users_pk", "PostgreSQL.localhost.OauthDB/index_publicusers_pk.htm")
f0_12_15 = gFld("public.usersroles_pk", "PostgreSQL.localhost.OauthDB/index_publicusersroles_pk.htm")
f0_12.addChildren([f0_12_0,f0_12_1,f0_12_2,f0_12_3,f0_12_4,f0_12_5,f0_12_6,f0_12_7,f0_12_8,f0_12_9,f0_12_10,f0_12_11,f0_12_12,f0_12_13,f0_12_14,f0_12_15])
f0_17 = gFld("Sequences", "PostgreSQL.localhost.OauthDB/allSequences.htm")
f0_17_0 = gFld("public.accesstokenid", "PostgreSQL.localhost.OauthDB/sequence_publicaccesstokenid.htm")
f0_17_1 = gFld("public.authorizationcodeid", "PostgreSQL.localhost.OauthDB/sequence_publicauthorizationcodeid.htm")
f0_17_2 = gFld("public.clientid", "PostgreSQL.localhost.OauthDB/sequence_publicclientid.htm")
f0_17_3 = gFld("public.logid", "PostgreSQL.localhost.OauthDB/sequence_publiclogid.htm")
f0_17_4 = gFld("public.refreshid", "PostgreSQL.localhost.OauthDB/sequence_publicrefreshid.htm")
f0_17_5 = gFld("public.roleid", "PostgreSQL.localhost.OauthDB/sequence_publicroleid.htm")
f0_17_6 = gFld("public.scopeid", "PostgreSQL.localhost.OauthDB/sequence_publicscopeid.htm")
f0_17_7 = gFld("public.userid", "PostgreSQL.localhost.OauthDB/sequence_publicuserid.htm")
f0_17.addChildren([f0_17_0,f0_17_1,f0_17_2,f0_17_3,f0_17_4,f0_17_5,f0_17_6,f0_17_7])
f0_21 = gFld("all table columns", "PostgreSQL.localhost.OauthDB/allTableColumns.htm")
f0_22 = gFld("all procedure params", "PostgreSQL.localhost.OauthDB/allProcedureParameters.htm")
f0.addChildren([f0_0,f0_3,f0_8,f0_10,f0_12,f0_17,f0_21,f0_22])

foldersTree.addChildren([f0])
foldersTree.treeID = "L1"
